tap 'caskroom/cask'

brew 'git'
brew 'node'
brew 'npm'
brew 'docker'
brew 'docker-machine'
brew 'docker-compose'
brew 'docker-machine-driver-xhyve'
brew 'antigen'
brew 'packer'
brew 'elasticsearch'
brew 'go'

cask 'chefdk'
cask 'virtualbox'
cask 'vmware-fusion'
cask 'vagrant'
cask 'vagrant-manager'
cask 'mamp'
cask 'opera'
cask 'firefox'
cask 'google-chrome'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'Atom'
cask 'webstorm'
cask 'sequel-pro'
cask 'robomongo'
cask 'mongodb'
cask 'openoffice'
cask 'skype-for-business'
cask 'sketch'
cask 'java'

mas 'Slack', id: 803453959
